train_file: "/data/home/wangyouze/dataset/flickr30k/data/ve_train.json"
val_file: /data/home/wangyouze/dataset/flickr30k/data/ve_dev.json"
test_file: "/data/home/wangyouze/dataset/flickr30k/data/ve_test.json"

image_root: "/data/home/wangyouze/dataset/flickr30k/"

image_res: 384
batch_size_train: 8
batch_size_test: 4

alpha: 0.4
distill: False
warm_up: False

epsilon: 2
num_iters: 10

bert_config: '/data/home/wangyouze/projects/Adversarial-Training-against-Multimodal-Adversarial-Attacks/adversarial_robustness_VE/configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}






